### ISSUE TITLE
Startup overloads the server

### ISSUE THREAD

**Issue by galaczi** [demyxco/demyx#9]
I have set up approximately 40 websites with demyx. Initially everything seemed to work fine. But after each server restart there is such a storm created by demyx that the server becomes totally unresponsive. 100% CPU and memory usage. I am afraid I won't be able to use demyx then even though I liked it a lot.

Ubuntu 18.04, 4vCPU, 8GB RAM

**Comment by demyxco** [comment]
So that would be 140 containers booting up in the Demyx stack, unfortunately there's nothing configured on Demyx with how Docker boot up sequence goes.

Where are you hosted? One of my servers boots up fine with 83 containers using Alpine Linux 3.12.0, 1 core, 4gb ram. Though I am using Alpine Linux as the host OS in all of my servers.

**Comment by galaczi** [comment]
It's a local company. Thanks for your reply anyway!

**Comment by demyxco** [comment]
Yeah sorry about that, I would recommend running Alpine Linux as the host for best performance. Demyx doesn’t really install or pollute anything on the host since everything is in the containers. Best of luck!

**Comment by demyxco** [comment]
Also feel free to come join us in Freenode: https://webchat.freenode.net/?channel=#demyx
